<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVkFRzF2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVkFRzF2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVkFRzF2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVkFRzF2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVkFRzF2\App_KernelDevDebugContainer([
    'container.build_hash' => 'VkFRzF2',
    'container.build_id' => 'bc3dac79',
    'container.build_time' => 1583249361,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVkFRzF2');
